### ISSUE TITLE
Invalid argument in generated promtail.service

### ISSUE THREAD

**Issue by arshesney** [escalate/ansible-raspberry-promtail-docker#1]
Generated promtail.service returns the error:
`docker: network-scoped aliases are only supported for user-defined networks`
and a warning:
`WARNING: Your kernel does not support memory limit capabilities or the cgroup is not mounted. Limitation discarded.`

Workaround is removing the `--network-alias=promtail \` line from service file.

System:
Raspbian GNU/Linux 11 (bullseye)
Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
Docker version 20.10.16, build aa7e414

Playbook used:
```yaml
- hosts:
  - raspberrypi
  become: true

  pre_tasks:
    - name: Install python3-docker
      apt:
        name: python3-docker
        state: present

  roles:
    - role: escalate.promtail
      tags: promtail
      vars:
        promtail_config:
          clients:
            - url: https://mylokiserver/loki/api/v1/push
```
